services:
  # Backend API - Produção
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: encantar-backend-prod
    env_file:
      - .env
    environment:
      # Banco PostgreSQL na máquina host
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRES_IN: "15m"
      JWT_REFRESH_EXPIRES_IN: "7d"
      PORT: 3001
      FRONTEND_URL: ${FRONTEND_URL}
      NODE_ENV: "production"
      LOG_LEVEL: "info"
      ENABLE_SEED: ${ENABLE_SEED:-false}
    ports:
      - "3001:3001"
    extra_hosts:
      # Permite acesso ao PostgreSQL na máquina host
      - "host.docker.internal:host-gateway"
    networks:
      - encantar-network-prod
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Frontend Next.js - Produção
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: encantar-frontend-prod
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - encantar-network-prod
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  encantar-network-prod:
    driver: bridge
